apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      # keyID and keySecretRef are used when a new private key needs to be generated
      keyID: {{ .Values.zerosslEabKid }}
      keySecretRef:
        name: zerossl-eab-hmac-key
        key: secret
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: zerossl-account-key
    solvers:
      - http01:
          ingress:
            class: public
        selector:
          dnsZones:
            - {{ .Values.externalDomain }}
      - dns01:
          cnameStrategy: Follow
          route53:
            region: {{ .Values.awsRegion }}
            role: {{ .Values.awsRole }}
        selector:
          dnsZones:
            - {{ .Values.internalDomain }}
