---
# Source: kronicle/charts/kronicle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-app
  labels:
    app: kronicle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-app
  template:
    metadata:
      labels:
        app: kronicle-app
    spec:
      containers:
        - name: kronicle-app
          image: ghcr.io/kronicle-tech/kronicle-app:1.2.3
          env:
            - name: "SERVER_SIDE_SERVICE_BASE_URL"
              value: "http://kronicle-service.test-namespace.svc.cluster.local"
            - name: "ANALYTICS_PLAUSIBLE_DATA_DOMAIN"
              value: "demo.external.example.com"
            - name: "ANALYTICS_PLAUSIBLE_ENABLED"
              value: "true"
            - name: "CLIENT_SIDE_SERVICE_BASE_URL"
              value: "https://demo-service.external.example.com"
            - name: "INTRO_MARKDOWN"
              value: "This is a live demo for [Kronicle](https://kronicle.tech). Kronicle is an open source system for\nvisualising and documenting a tech stack, including software and infrastructure.\n\nInteresting pages in the demo:\n\n1. [An interactive, dynamically generated dependencies diagram](/all-components/dependencies) that shows all the components in the demo tech stack and how they connect to each other.  Try hovering over items in the diagram and using the filters on the right hand side.\n2. [A list of all the components in the demo tech stack](/all-components).  Try using the filters on the right hand side.\n3. Kronicle fully supports OpenAPI specs.  Kronicle can download OpenAPI specs hosted on a service's endpoint (e.g. with Springdoc) and then [hostes a copy of those OpenAPI specs](/all-components/openapi-specs).  Click a link in the `Link` column on that page to view an individual OpenAPI spec rendered using Redoc.\n4. [A list of all the components owned by a team](/teams/kronicle-project/components)\n5. [Dependencies diagram for an individual component](/components/kronicle-service/dependencies).  Use the radius dropdown on the right hand side to see more of the tech stack that surrounds the component.\n6. [A component's page which shows the \"key software\" used by the component and other important information](/components/kronicle-service).  Kronicle automatically scans Gradle build scripts (npm support coming soon) to find the key software used by the component.\n7. [All the tech debt for the tech stack](/all-components/tech-debts)\n8. [All the cross functional requirements (NFRs) for a team](/teams/kronicle-project/cross-functional-requirements)\n9. [Response times for any components using Zipkin for distributed tracing](/components/kronicle-service/response-times).\n"
            - name: "INTRO_TITLE"
              value: "Kronicle Live Demo"
          ports:
            - containerPort: 3000
---
# Source: kronicle/charts/kronicle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-service
  labels:
    app: kronicle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-service
  template:
    metadata:
      labels:
        app: kronicle-service
    spec:
      containers:
        - name: kronicle-service
          image: ghcr.io/kronicle-tech/kronicle-service:1.2.3
          env:
            - name: "KEY_SOFTWARE_RULES_0_NAME"
              value: "Gradle"
            - name: "KEY_SOFTWARE_RULES_0_SOFTWARE_NAME_PATTERN"
              value: "^gradle-wrapper$"
            - name: "KEY_SOFTWARE_RULES_10_NAME"
              value: "Micronaut"
            - name: "KEY_SOFTWARE_RULES_10_SOFTWARE_NAME_PATTERN"
              value: "^io.micronaut:micronaut-bom$"
            - name: "KEY_SOFTWARE_RULES_1_NAME"
              value: "Spring Boot"
            - name: "KEY_SOFTWARE_RULES_1_SOFTWARE_NAME_PATTERN"
              value: "^org.springframework.boot:"
            - name: "KEY_SOFTWARE_RULES_2_NAME"
              value: "Guava"
            - name: "KEY_SOFTWARE_RULES_2_SOFTWARE_NAME_PATTERN"
              value: "^com.google.guava:guava$"
            - name: "KEY_SOFTWARE_RULES_3_NAME"
              value: "Zipkin Brave"
            - name: "KEY_SOFTWARE_RULES_3_SOFTWARE_NAME_PATTERN"
              value: "^io.zipkin.brave:brave$"
            - name: "KEY_SOFTWARE_RULES_4_NAME"
              value: "Dropwizard"
            - name: "KEY_SOFTWARE_RULES_4_SOFTWARE_NAME_PATTERN"
              value: "^io.dropwizard:dropwizard-core$"
            - name: "KEY_SOFTWARE_RULES_5_NAME"
              value: "MongoDB Driver"
            - name: "KEY_SOFTWARE_RULES_5_SOFTWARE_NAME_PATTERN"
              value: "^org.mongodb:(mongodb-driver|mongo-java-driver)$"
            - name: "KEY_SOFTWARE_RULES_6_NAME"
              value: "Jackson"
            - name: "KEY_SOFTWARE_RULES_6_SOFTWARE_NAME_PATTERN"
              value: "^com.fasterxml.jackson.core:"
            - name: "KEY_SOFTWARE_RULES_7_NAME"
              value: "Spring Cloud"
            - name: "KEY_SOFTWARE_RULES_7_SOFTWARE_NAME_PATTERN"
              value: "^org.springframework.cloud:spring-cloud-dependencies$"
            - name: "KEY_SOFTWARE_RULES_8_NAME"
              value: "Lombok"
            - name: "KEY_SOFTWARE_RULES_8_SOFTWARE_NAME_PATTERN"
              value: "^org.projectlombok:lombok$"
            - name: "KEY_SOFTWARE_RULES_9_NAME"
              value: "Kotlin"
            - name: "KEY_SOFTWARE_RULES_9_SOFTWARE_NAME_PATTERN"
              value: "^org.jetbrains.kotlin:kotlin-bom$"
            - name: "OPENAPI_SPEC_CLEAR_EXISTING_SERVERS"
              value: "true"
            - name: "OPENAPI_SPEC_SERVERS_0_DESCRIPTION"
              value: "The demo instance of Kronicle Service"
            - name: "OPENAPI_SPEC_SERVERS_0_URL"
              value: "https://demo-service.external.example.com"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_0_ACCOUNT_NAME"
              value: "kronicle-tech"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_1_ACCOUNT_NAME"
              value: "kronicle-computers"
            - name: "REPO_FINDERS_IGNORED_REPOS_0_URL"
              value: "https://github.com/kronicle-tech/kronicle-metadata-repo-template.git"
            - name: "REPO_FINDERS_IGNORED_REPOS_1_URL"
              value: "https://github.com/kronicle-tech/kronicle-metadata-codebase-template.git"
            - name: "SONARQUBE_BASE_URL"
              value: "https://sonarcloud.io"
            - name: "SONARQUBE_ORGANIZATIONS_0"
              value: "kronicle-tech"
            - name: "ZIPKIN_BASE_URL"
              value: "http://zipkin.zipkin.svc.cluster.local"
            - name: "ZIPKIN_SAMPLE_RATE"
              value: "1.0"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_0_PERSONAL_ACCESS_TOKEN_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "kronicle-service-config"
                  key: "github-repo-finder-username"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_0_PERSONAL_ACCESS_TOKEN_VALUE"
              valueFrom:
                secretKeyRef:
                  name: "kronicle-service-config"
                  key: "github-repo-finder-personal-access-token"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_1_PERSONAL_ACCESS_TOKEN_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "kronicle-service-config"
                  key: "github-repo-finder-username"
            - name: "REPO_FINDERS_GITHUB_ORGANIZATIONS_1_PERSONAL_ACCESS_TOKEN_VALUE"
              valueFrom:
                secretKeyRef:
                  name: "kronicle-service-config"
                  key: "github-repo-finder-personal-access-token"
          ports:
            - containerPort: 8090
