apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      role: {{ .Values.awsRole }}
      region: {{ .Values.awsRegion }}
