apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-service
  labels:
    app: kronicle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-service
  template:
    metadata:
      labels:
        app: kronicle-service
    spec:
      containers:
        - name: kronicle-service
          image: ghcr.io/kronicle-tech/kronicle-service:{{ .Values.kronicleServiceImageTag }}
          env:
            - name: REPO_FINDERS_IGNORED_REPOS_0_URL
              value: https://github.com/kronicle-tech/kronicle-metadata-repo-template.git
            - name: REPO_FINDERS_IGNORED_REPOS_1_URL
              value: https://github.com/kronicle-tech/kronicle-metadata-codebase-template.git
            - name: REPO_FINDERS_GITHUB_USERS_0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kronicle-service-config
                  key: github-repo-finder-username
            - name: REPO_FINDERS_GITHUB_USERS_0_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kronicle-service-config
                  key: github-repo-finder-personal-access-token
            - name: ZIPKIN_BASE_URL
              value: http://zipkin.zipkin.svc.cluster.local
          ports:
            - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-app
  labels:
    app: kronicle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-app
  template:
    metadata:
      labels:
        app: kronicle-app
    spec:
      containers:
        - name: kronicle-app
          image: ghcr.io/kronicle-tech/kronicle-app:{{ .Values.kronicleAppImageTag }}
          env:
            - name: CLIENT_SIDE_SERVICE_BASE_URL
              value: https://demo-service.{{ .Values.externalDomain }}
            - name: SERVER_SIDE_SERVICE_BASE_URL
              value: http://kronicle-service.kronicle.svc.cluster.local
          ports:
            - containerPort: 3000
