apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: kronicle-service-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: kronicle-service-config
    creationPolicy: Owner
  dataFrom:
    - key: {{ .Values.secretsManagerSecretName }}
