apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: kronicle-service
spec:
  provider:
    aws:
      service: SecretsManager
      role: {{ .Values.externalSecrets.awsRole }}
      region: {{ .Values.externalSecrets.awsRegion }}
