---
# Source: cert-manager-config/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
    # Used when a new private key needs to be generated
    #keyID: "test1234"
    #keySecretRef:
    #  name: zerossl-eab-hmac-key
    #  key: secret
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: zerossl-account-key
    solvers:
      - http01:
          ingress:
            class: public
        selector:
          dnsZones:
            - external.example.com
      - dns01:
          cnameStrategy: Follow
          route53:
            region: ${aws_region}
            role: ${cert_manager_role}
        selector:
          dnsZones:
            - internal.example.com
