---
# Source: cert-manager-config/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
    # keyID and keySecretRef are used when a new private key needs to be generated
    keyID: test1234
    keySecretRef:
      name: zerossl-eab-hmac-key
      key: secret
    disableAccountKeyGeneration: false
    privateKeySecretRef:
      name: zerossl-account-key
    solvers:
      - http01:
          ingress:
            class: public
        selector:
          dnsZones:
            - external.example.com
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-west-1
            role: arn:aws:iam::1234:role/external-secrets-example-role
        selector:
          dnsZones:
            - internal.example.com
