---
# Source: cert-manager-config/templates/external-secret.yaml
#apiVersion: external-secrets.io/v1alpha1
#kind: ExternalSecret
#metadata:
#  name: zerossl-eab-hmac-key
#spec:
#  refreshInterval: 1h
#  secretStoreRef:
#    name: secrets-manager
#    kind: ClusterSecretStore
#  target:
#    name: zerossl-eab-hmac-key
#    creationPolicy: Owner
#  data:
#    - secretKey: secret
#      remoteRef:
#        key: test-secret-name
#        property: zerossl-eab-hmac-key
---
# Source: cert-manager-config/templates/external-secret.yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: zerossl-account-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: zerossl-account-key
    creationPolicy: Owner
  template:
    type: kubernetes.io/tls
    data:
      tls.key: "{{ .tls.key }}"
  data:
    - secretKey: tls.key
      remoteRef:
        key: test-secret-name
        property: zerossl-account-key
