#apiVersion: external-secrets.io/v1alpha1
#kind: ExternalSecret
#metadata:
#  name: zerossl-eab-hmac-key
#spec:
#  refreshInterval: 1h
#  secretStoreRef:
#    name: secrets-manager
#    kind: ClusterSecretStore
#  target:
#    name: zerossl-eab-hmac-key
#    creationPolicy: Owner
#  data:
#    - secretKey: secret
#      remoteRef:
#        key: {{ .Values.secretsManagerSecretName }}
#        property: zerossl-eab-hmac-key
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: zerossl-account-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: zerossl-account-key
    creationPolicy: Owner
  data:
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.secretsManagerSecretName }}
        property: zerossl-account-key
