apiVersion: v2
name: kronicle
description: Deploys Helm chart for external-secrets https://external-secrets.io
type: application
version: 0.1.0
dependencies:
  - name: external-secrets
    # Run the following commands to find the latest chart version:
    # $ helm repo add external-secrets https://charts.external-secrets.io
    # $ helm search repo external-secrets
    version: 0.3.5
    repository: https://charts.external-secrets.io
