---
# Source: kronicle/charts/kronicle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-app
  labels:
    app: kronicle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-app
  template:
    metadata:
      labels:
        app: kronicle-app
    spec:
      containers:
        - name: kronicle-app
          image: ghcr.io/kronicle-tech/kronicle-app:1.2.3
          env:
            - name: "SERVER_SIDE_SERVICE_BASE_URL"
              value: "http://kronicle-service.test-namespace.svc.cluster.local"
            - name: "ANALYTICS_PLAUSIBLE_DATA_DOMAIN"
              value: "empty.external.example.com"
            - name: "ANALYTICS_PLAUSIBLE_ENABLED"
              value: "true"
            - name: "CLIENT_SIDE_SERVICE_BASE_URL"
              value: "https://empty-service.external.example.com"
            - name: "INTRO_MARKDOWN"
              value: "This is an empty instance of [Kronicle](https://kronicle.tech) that uses\nhttps://github.com/kronicle-tech/kronicle-helm-charts for deployment to Kubernetes.\n\nSee https://demo.kronicle.tech for a more full featured deployment of Kronicle.\n"
            - name: "INTRO_TITLE"
              value: "Kronicle Empty Instance"
          ports:
            - containerPort: 3000
---
# Source: kronicle/charts/kronicle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronicle-service
  labels:
    app: kronicle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronicle-service
  template:
    metadata:
      labels:
        app: kronicle-service
    spec:
      containers:
        - name: kronicle-service
          image: ghcr.io/kronicle-tech/kronicle-service:1.2.3
          env:
          ports:
            - containerPort: 8090
