---
# Source: external-secrets-config/templates/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      role: arn:aws:iam::1234:role/example-role
      region: us-west-1
