apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: ghcr.io/openzipkin/zipkin-slim:{{ .Values.zipkinImageTag }}
          env:
            - name: STORAGE_TYPE
              value: elasticsearch
              # This setting is important for Kronicle to be able to query Zipkin reliably
            - name: QUERY_TIMEOUT
              value: "70s"
            - name: ES_HOSTS
              value: https://zipkin-elasticsearch-es-http.zipkin.svc.cluster.local:9200
              # This setting is important for Kronicle to be able to query Zipkin reliably
            - name: ES_TIMEOUT
              value: "60000"  # Unit is milliseconds
              # No point setting higher than 1 as running on a single node k8s cluster
            - name: ES_INDEX_SHARDS
              value: "1"
            - name: ES_USERNAME
              value: elastic
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zipkin-elasticsearch-es-elastic-user
                  key: elastic
            - name: ES_SSL_NO_VERIFY
              value: "true"
          ports:
            - containerPort: 9411
