apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: zipkin-elasticsearch
spec:
  version: {{ .Values.elasticsearchImageTag }}
  nodeSets:
    - name: zipkin-elasticsearch
      count: 1
      config:
        node.store.allow_mmap: false
